# Generated by Django 3.0.6 on 2020-07-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
                ('identidade', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
